// Somente a chave publishable é usada no navegador. Nunca coloque sb_secret aqui.
const API='https://kgrarnsvumylmlhjrxwe.supabase.co';
const KEY='sb_publishable_kC5QPgf0PvC-7HWu-33iYQ_JgSZqHXG';
const $=s=>document.querySelector(s), state={session:null,companyId:null,role:null,products:[]};
const status=(message,error=false)=>{const el=$('#status');el.textContent=message;el.className=error?'error':'success'};
const headers=(auth=false)=>({'apikey':KEY,'Content-Type':'application/json',...(auth&&state.session?{'Authorization':`Bearer ${state.session.access_token}`}:{})});
async function request(path,{method='GET',body,auth=false,prefer}={}){const res=await fetch(API+path,{method,headers:{...headers(auth),...(prefer?{'Prefer':prefer}:{})},body:body?JSON.stringify(body):undefined});let data=await res.json().catch(()=>null);if(!res.ok)throw Error(data?.msg||data?.message||data?.error_description||data?.error||`Erro HTTP ${res.status}`);return data}
function persist(s){state.session=s;if(s)sessionStorage.setItem('terra_nova_session',JSON.stringify(s));else sessionStorage.removeItem('terra_nova_session')}
async function ensureSession(){const s=state.session;if(!s)return false;if(s.expires_at&&Date.now()/1000<s.expires_at-60)return true;if(!s.refresh_token)return false;try{const n=await request('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:s.refresh_token}});persist({...n,expires_at:Math.floor(Date.now()/1000)+n.expires_in});return true}catch{persist(null);return false}}
async function rest(table,query='',opts={}){if(!await ensureSession())throw Error('Sessão encerrada. Entre novamente.');return request(`/rest/v1/${table}${query}`,{...opts,auth:true})}
async function load(){if(!await ensureSession()){showLogin();return}$('#login').hidden=true;$('#workspace').hidden=false;$('#identity').textContent=state.session.user?.email||'';try{const memberships=await rest('memberships',`?select=company_id,role&user_id=eq.${encodeURIComponent(state.session.user.id)}`);if(!memberships.length){$('#data').hidden=true;$('#company-name').textContent='Aguardando vínculo de administrador';status('Login confirmado. Falta vincular seu usuário à Terra Nova no banco.');return}state.companyId=memberships[0].company_id;state.role=memberships[0].role;const companies=await rest('companies',`?select=name&id=eq.${state.companyId}`);$('#company-name').textContent=companies[0]?.name||'Terra Nova';$('#data').hidden=false;await loadStock();status('Conectado ao banco com acesso '+state.role+'.')}catch(e){status(e.message,true)}}
function showLogin(){$('#login').hidden=false;$('#workspace').hidden=true}
const money=n=>Number(n).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
async function loadStock(){state.products=await rest('products',`?select=id,name,base_unit&company_id=eq.${state.companyId}&order=name`);const sel=$('#product-select');sel.replaceChildren(...state.products.map(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=p.name+' ('+p.base_unit+')';return o}));const lots=await rest('stock_lots',`?select=product_id,quantity,expires_on,unit_cost&company_id=eq.${state.companyId}&order=expires_on.asc`);const tbody=$('#lots');tbody.replaceChildren(...lots.map(l=>{const tr=document.createElement('tr');for(const v of [state.products.find(p=>p.id===l.product_id)?.name||'',l.quantity,l.expires_on,money(l.unit_cost)]){const td=document.createElement('td');td.textContent=v;tr.append(td)}return tr}))}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter,form=e.currentTarget,d=Object.fromEntries(new FormData(form));try{if(b?.value==='signup'){await request('/auth/v1/signup',{method:'POST',body:{email:d.email,password:d.password}});status('Cadastro solicitado. Confirme o e-mail recebido e depois clique em Entrar.');return}const s=await request('/auth/v1/token?grant_type=password',{method:'POST',body:{email:d.email,password:d.password}});persist({...s,expires_at:Math.floor(Date.now()/1000)+s.expires_in});form.reset();await load()}catch(err){status(err.message,true)}});
$('#logout').addEventListener('click',async()=>{try{if(state.session)await request('/auth/v1/logout',{method:'POST',auth:true})}catch{}persist(null);state.companyId=null;showLogin();status('Sessão encerrada.')});
$('#product-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,d=Object.fromEntries(new FormData(form));try{await rest('products','',{method:'POST',body:{company_id:state.companyId,name:d.name.trim(),base_unit:d.base_unit},prefer:'return=minimal'});form.reset();await loadStock();status('Produto salvo no banco.')}catch(err){status(err.message,true)}});
$('#lot-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,d=Object.fromEntries(new FormData(form)),qty=Number(d.quantity),cost=Number(d.base_cost),tax=Number(d.entry_tax_percent);if(!(qty>0&&cost>=0&&tax>=0&&tax<=3))return status('Confira quantidade, custo e taxa de 0% a 3%.',true);try{await rest('stock_lots','',{method:'POST',body:{company_id:state.companyId,product_id:d.product_id,quantity:qty,expires_on:d.expires_on,unit_cost:Math.round(cost*(1+tax/100)*10000)/10000,entry_tax_percent:tax,invoice_number:d.invoice_number||null},prefer:'return=minimal'});form.reset();await loadStock();status('Lote salvo no banco.')}catch(err){status(err.message,true)}});
try{persist(JSON.parse(sessionStorage.getItem('terra_nova_session')||'null'))}catch{persist(null)}load();
